name: cURL SBOM Application

on:
  workflow_dispatch:
    inputs:
      operation:
        type: choice
        description: Operation
        options: 
        - upload
        - status
        required: true
    secrets:
      sn-instance-url:
        required: true
  workflow_call:
    inputs:
      operation:
        type: string
        required: true
        description: The kind of operation to perform
      document:
        type: string
        required: false
        description: The SBOM document to be uploaded.
    secrets:
      sn-instance-url:
        required: true
      sn-sbom-username:
        required: true
      sn-sbom-password:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ inputs.operation }} == 'upload'
    steps:
    - name: Upload
      run: echo "Detected an upload operation -> ${{ inputs.operation }}"
    - name: Perform CURL to Vulnerability Response Application
      run: |
        response=$(curl -i -f -s -w "\n%{response_code}" \             
             -H 'Content-Type: application/json' \
             -d '${{ inputs.document }}' \
             ${{ secrets.sn-instance-url}}/api/sbom/core/upload \
             -u ${{ secrets.sn-sbom-username }}:${{ secrets.sn-sbom-password }} \
        )
        data=$(echo "$response" | awk '{$NF=""; sub(/[[:space:]]+$/, "")}1')
        status_code=$(echo "$response" | awk '{print $NF}')

        echo DATA "$data"
        echo STATUS_CODE "$status_code"

  status:
    runs-on: ubuntu-latest
    if: ${{ inputs.operation }} == 'status'
    steps:
    - name: Status
      run: echo "Detected a status operation -> ${{ inputs.operation }}"
