name: cURL SBOM Application

on:
  workflow_dispatch:
    inputs:
      operation:
        type: choice
        description: Operation
        options: 
        - upload
        - status
        required: true
    secrets:
      sn-instance-url:
        required: true
  workflow_call:
    inputs:
      operation:
        type: string
        required: true
        description: The kind of operation to perform
    secrets:
      sn-instance-url:
        required: true


jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ inputs.operation }} == 'upload'
    steps:
    - name: Upload
      run: echo "Detected an upload operation -> ${{ inputs.operation }}, ${{ env.sn-instance-url }}"
  status:
    runs-on: ubuntu-latest
    if: ${{ inputs.operation }} == 'status'
    steps:
    - name: Status
      run: echo "Detected a status operation -> ${{ inputs.operation }}"
