name: Validate Input Arguments

on: [workflow_dispatch, workflow_call, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: jack-gronenthal-sn/sbom-action-beta
          path: service-now
          ref: json-input
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: |
          cd $GITHUB_WORKSPACE/service-now/
          npm install
          npm run sanity